Console.WriteLine("Enter number1");
int number1 = Convert.ToInt16(Console.ReadLine());
Console.WriteLine("Enter number2");
int number2 = Convert.ToInt16(Console.ReadLine());
Console.WriteLine("Enter number3");
int number3 = Convert.ToInt16(Console.ReadLine());
int max = number1;
if (number2 > max) max = number2;
if (number3 > max) max = number3;
System.Console.WriteLine (max);